### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by vmachacek** [akirk/StatusBarJsonPath#1]
sorry for noob question, but how to you install it?

**Comment by akirk** [comment]
Ideally through Package Control but my PR there has not been accepted yet: https://github.com/wbond/package_control_channel/pull/8372

So basically it's:
1. Click the *Preferences >Browse Packages…* menu, this should open a folder `Packages`.
2. Download https://github.com/akirk/StatusBarJsonPath/archive/refs/heads/main.zip and extract it into that directory (it should then have a subfolder `StatusBarJsonPath-main`).
3. Restart Sublime Text.
